export enum CustomerDocumentType {
  DNI = 'DNI',
  CUIT = 'CUIT',
}

export enum CustomerErrorCode {
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  CUSTOMER_DOCUMENT_INVALID = 'CUSTOMER_DOCUMENT_INVALID',
  CUSTOMER_DOCUMENT_ALREADY_EXISTS = 'CUSTOMER_DOCUMENT_ALREADY_EXISTS',
  CUSTOMER_TAX_CONDITION_INCOMPATIBLE = 'CUSTOMER_TAX_CONDITION_INCOMPATIBLE',
  CUSTOMER_INVALID_CREDIT_LIMIT = 'CUSTOMER_INVALID_CREDIT_LIMIT',
  CUSTOMER_INVALID_GENERAL_DISCOUNT = 'CUSTOMER_INVALID_GENERAL_DISCOUNT',
  CUSTOMER_NO_EFFECTIVE_CHANGES = 'CUSTOMER_NO_EFFECTIVE_CHANGES',
  CUSTOMER_ALREADY_INACTIVE = 'CUSTOMER_ALREADY_INACTIVE',
  CUSTOMER_ALREADY_ACTIVE = 'CUSTOMER_ALREADY_ACTIVE',
  CUSTOMER_FORBIDDEN_CREDIT_LIMIT = 'CUSTOMER_FORBIDDEN_CREDIT_LIMIT',
  CUSTOMER_FORBIDDEN_GENERAL_DISCOUNT = 'CUSTOMER_FORBIDDEN_GENERAL_DISCOUNT',
  CUSTOMER_FORBIDDEN_FIELD_UPDATE = 'CUSTOMER_FORBIDDEN_FIELD_UPDATE',
  CUSTOMER_CONCURRENCY_CONFLICT = 'CUSTOMER_CONCURRENCY_CONFLICT',
}

export type CustomerSortField =
  'businessName' | 'cuitOrDni' | 'taxCondition' | 'creditLimit' | 'createdAt' | 'updatedAt';
