export enum CustomerSpecialPriceMode {
  FIXED_PRICE = 'FIXED_PRICE',
  DISCOUNT_PERCENTAGE = 'DISCOUNT_PERCENTAGE',
}

export enum CustomerPricingRuleApplied {
  FIXED_PRICE = 'FIXED_PRICE',
  PRODUCT_DISCOUNT = 'PRODUCT_DISCOUNT',
  GENERAL_DISCOUNT = 'GENERAL_DISCOUNT',
  CATALOG_PRICE = 'CATALOG_PRICE',
}

export enum CustomerPricingErrorCode {
  CUSTOMER_SPECIAL_PRICE_NOT_FOUND = 'CUSTOMER_SPECIAL_PRICE_NOT_FOUND',
  CUSTOMER_SPECIAL_PRICE_ALREADY_EXISTS = 'CUSTOMER_SPECIAL_PRICE_ALREADY_EXISTS',
  CUSTOMER_SPECIAL_PRICE_INVALID_MODE = 'CUSTOMER_SPECIAL_PRICE_INVALID_MODE',
  CUSTOMER_SPECIAL_PRICE_INVALID_PRICE = 'CUSTOMER_SPECIAL_PRICE_INVALID_PRICE',
  CUSTOMER_SPECIAL_PRICE_INVALID_DISCOUNT = 'CUSTOMER_SPECIAL_PRICE_INVALID_DISCOUNT',
  CUSTOMER_SPECIAL_PRICE_NO_EFFECTIVE_CHANGES = 'CUSTOMER_SPECIAL_PRICE_NO_EFFECTIVE_CHANGES',
  CUSTOMER_PRICING_CUSTOMER_NOT_FOUND = 'CUSTOMER_PRICING_CUSTOMER_NOT_FOUND',
  CUSTOMER_PRICING_CUSTOMER_INACTIVE = 'CUSTOMER_PRICING_CUSTOMER_INACTIVE',
  CUSTOMER_PRICING_PRODUCT_NOT_FOUND = 'CUSTOMER_PRICING_PRODUCT_NOT_FOUND',
  CUSTOMER_PRICING_PRODUCT_INACTIVE = 'CUSTOMER_PRICING_PRODUCT_INACTIVE',
  CUSTOMER_SPECIAL_PRICE_CONCURRENCY_CONFLICT = 'CUSTOMER_SPECIAL_PRICE_CONCURRENCY_CONFLICT',
}
