export enum ImporterErrorCode {
  IMPORTER_FILE_MISSING = 'IMPORTER_FILE_MISSING',
  IMPORTER_FILE_EMPTY = 'IMPORTER_FILE_EMPTY',
  IMPORTER_FILE_TOO_LARGE = 'IMPORTER_FILE_TOO_LARGE',
  IMPORTER_FORMAT_NOT_SUPPORTED = 'IMPORTER_FORMAT_NOT_SUPPORTED',
  IMPORTER_MIME_MISMATCH = 'IMPORTER_MIME_MISMATCH',
  IMPORTER_FILE_CORRUPT = 'IMPORTER_FILE_CORRUPT',
  IMPORTER_ZIP_SUSPICIOUS = 'IMPORTER_ZIP_SUSPICIOUS',
  IMPORTER_MACROS_NOT_ALLOWED = 'IMPORTER_MACROS_NOT_ALLOWED',
  IMPORTER_FORMULA_IN_HEADER = 'IMPORTER_FORMULA_IN_HEADER',
  IMPORTER_FORMULA_IN_DATA = 'IMPORTER_FORMULA_IN_DATA',
  IMPORTER_EXCEL_ERROR_CELL = 'IMPORTER_EXCEL_ERROR_CELL',
  IMPORTER_ROW_LIMIT_EXCEEDED = 'IMPORTER_ROW_LIMIT_EXCEEDED',
  IMPORTER_COLUMN_LIMIT_EXCEEDED = 'IMPORTER_COLUMN_LIMIT_EXCEEDED',
  IMPORTER_HEADER_EMPTY = 'IMPORTER_HEADER_EMPTY',
  IMPORTER_HEADER_DUPLICATE = 'IMPORTER_HEADER_DUPLICATE',
  IMPORTER_MULTIPLE_SHEETS = 'IMPORTER_MULTIPLE_SHEETS',
  IMPORTER_SUPPLIER_NOT_FOUND = 'IMPORTER_SUPPLIER_NOT_FOUND',
  IMPORTER_SUPPLIER_INACTIVE = 'IMPORTER_SUPPLIER_INACTIVE',

  // S3-US13-B Template & Mapping Domain Errors
  IMPORTER_TEMPLATE_NOT_FOUND = 'IMPORTER_TEMPLATE_NOT_FOUND',
  IMPORTER_TEMPLATE_NAME_DUPLICATE = 'IMPORTER_TEMPLATE_NAME_DUPLICATE',
  IMPORTER_TEMPLATE_FINGERPRINT_DUPLICATE = 'IMPORTER_TEMPLATE_FINGERPRINT_DUPLICATE',
  IMPORTER_INVALID_MAPPING = 'IMPORTER_INVALID_MAPPING',
  IMPORTER_MAPPING_MISSING_REQUIRED_FIELD = 'IMPORTER_MAPPING_MISSING_REQUIRED_FIELD',
  IMPORTER_MAPPING_HEADER_NOT_FOUND = 'IMPORTER_MAPPING_HEADER_NOT_FOUND',
  IMPORTER_MAPPING_DUPLICATE_COLUMN = 'IMPORTER_MAPPING_DUPLICATE_COLUMN',
  IMPORTER_FINGERPRINT_MISMATCH = 'IMPORTER_FINGERPRINT_MISMATCH',

  // S3-US14-A Preview & Checksum Errors
  IMPORTER_CHECKSUM_MISMATCH = 'IMPORTER_CHECKSUM_MISMATCH',
  IMPORTER_MAPPING_INVALID_JSON = 'IMPORTER_MAPPING_INVALID_JSON',
}

export enum ImporterRowErrorCode {
  // SKU Errors
  ROW_SKU_EMPTY = 'ROW_SKU_EMPTY',
  ROW_SKU_DUPLICATE = 'ROW_SKU_DUPLICATE',
  ROW_SKU_TOO_LONG = 'ROW_SKU_TOO_LONG',

  // Cost Errors
  ROW_COST_EMPTY = 'ROW_COST_EMPTY',
  ROW_COST_NOT_NUMERIC = 'ROW_COST_NOT_NUMERIC',
  ROW_COST_AMBIGUOUS_FORMAT = 'ROW_COST_AMBIGUOUS_FORMAT',
  ROW_COST_ZERO = 'ROW_COST_ZERO',
  ROW_COST_NEGATIVE = 'ROW_COST_NEGATIVE',
  ROW_COST_EXCEEDS_DECIMALS = 'ROW_COST_EXCEEDS_DECIMALS',
  ROW_COST_EXCEEDS_MAX = 'ROW_COST_EXCEEDS_MAX',

  // Quantity Errors
  ROW_QUANTITY_NOT_NUMERIC = 'ROW_QUANTITY_NOT_NUMERIC',
  ROW_QUANTITY_ZERO_OR_NEGATIVE = 'ROW_QUANTITY_ZERO_OR_NEGATIVE',
  ROW_QUANTITY_EXCEEDS_DECIMALS = 'ROW_QUANTITY_EXCEEDS_DECIMALS',

  // Unit & Relation Errors
  ROW_UNIT_EMPTY = 'ROW_UNIT_EMPTY',
  ROW_UNIT_INCOMPATIBLE = 'ROW_UNIT_INCOMPATIBLE',
  ROW_ASSOCIATED_PRODUCT_INACTIVE = 'ROW_ASSOCIATED_PRODUCT_INACTIVE',

  // Formula & Cell Errors
  ROW_FORMULA_NOT_ALLOWED = 'ROW_FORMULA_NOT_ALLOWED',
  ROW_CELL_VALUE_INVALID = 'ROW_CELL_VALUE_INVALID',
}
