export enum PriceReviewStatus {
  PENDIENTE = 'PENDIENTE',
  APROBADO = 'APROBADO',
  RECHAZADO = 'RECHAZADO',
  POSPUESTO = 'POSPUESTO',
}

export enum PriceReviewApprovalMode {
  SUGGESTED = 'SUGGESTED',
  CUSTOM = 'CUSTOM',
}

export enum PriceReviewDecisionAction {
  APPROVE_SUGGESTED = 'APPROVE_SUGGESTED',
  APPROVE_CUSTOM = 'APPROVE_CUSTOM',
  REJECT = 'REJECT',
  POSTPONE = 'POSTPONE',
  REOPEN = 'REOPEN',
}

export enum PriceReviewStaleReason {
  SUPERSEDED = 'SUPERSEDED',
  COST_CHANGED = 'COST_CHANGED',
  SUGGESTED_PRICE_CHANGED = 'SUGGESTED_PRICE_CHANGED',
  ACTIVE_PRICE_CHANGED = 'ACTIVE_PRICE_CHANGED',
}

export enum PriceReviewErrorCode {
  PRICE_REVIEW_NOT_FOUND = 'PRICE_REVIEW_NOT_FOUND',
  PRICE_REVIEW_PRODUCT_NOT_FOUND = 'PRICE_REVIEW_PRODUCT_NOT_FOUND',
  PRICE_REVIEW_INVALID_TRANSITION = 'PRICE_REVIEW_INVALID_TRANSITION',
  PRICE_REVIEW_STALE = 'PRICE_REVIEW_STALE',
  PRICE_REVIEW_INVALID_CUSTOM_PRICE = 'PRICE_REVIEW_INVALID_CUSTOM_PRICE',
  PRICE_REVIEW_INVALID_REASON = 'PRICE_REVIEW_INVALID_REASON',
  PRICE_REVIEW_INVALID_DATE_RANGE = 'PRICE_REVIEW_INVALID_DATE_RANGE',
  PRICE_REVIEW_CONCURRENCY_CONFLICT = 'PRICE_REVIEW_CONCURRENCY_CONFLICT',
}

export enum MarkupLevel {
  GLOBAL = 'GLOBAL',
  CATEGORY = 'CATEGORY',
  PRODUCT = 'PRODUCT',
}

export enum MarkupErrorCode {
  MARKUP_NOT_FOUND = 'MARKUP_NOT_FOUND',
  MARKUP_ALREADY_EXISTS = 'MARKUP_ALREADY_EXISTS',
  MARKUP_INVALID_TARGET = 'MARKUP_INVALID_TARGET',
  MARKUP_INVALID_PERCENTAGE = 'MARKUP_INVALID_PERCENTAGE',
  MARKUP_GLOBAL_MISSING = 'MARKUP_GLOBAL_MISSING',
  MARKUP_GLOBAL_CANNOT_BE_DELETED = 'MARKUP_GLOBAL_CANNOT_BE_DELETED',
  MARKUP_TARGET_INACTIVE = 'MARKUP_TARGET_INACTIVE',
}
