export enum PriceReviewStatus {
  PENDIENTE = 'PENDIENTE',
  APROBADO = 'APROBADO',
  RECHAZADO = 'RECHAZADO',
  POSPUESTO = 'POSPUESTO',
}

export enum MarkupLevel {
  GLOBAL = 'GLOBAL',
  CATEGORY = 'CATEGORY',
  PRODUCT = 'PRODUCT',
}

export enum MarkupErrorCode {
  MARKUP_NOT_FOUND = 'MARKUP_NOT_FOUND',
  MARKUP_ALREADY_EXISTS = 'MARKUP_ALREADY_EXISTS',
  MARKUP_INVALID_TARGET = 'MARKUP_INVALID_TARGET',
  MARKUP_INVALID_PERCENTAGE = 'MARKUP_INVALID_PERCENTAGE',
  MARKUP_GLOBAL_MISSING = 'MARKUP_GLOBAL_MISSING',
  MARKUP_GLOBAL_CANNOT_BE_DELETED = 'MARKUP_GLOBAL_CANNOT_BE_DELETED',
  MARKUP_TARGET_INACTIVE = 'MARKUP_TARGET_INACTIVE',
}
