export enum ProductImportBatchResult {
  COMPLETED = 'COMPLETED',
}

export enum ProductBulkLoadRowStatus {
  VALID = 'VALID',
  INVALID = 'INVALID',
}

export enum ProductBulkFileErrorCode {
  BULK_LOAD_MISSING_FILE = 'BULK_LOAD_MISSING_FILE',
  BULK_LOAD_INVALID_FILE = 'BULK_LOAD_INVALID_FILE',
  BULK_LOAD_UNSUPPORTED_TYPE = 'BULK_LOAD_UNSUPPORTED_TYPE',
  BULK_LOAD_FILE_TOO_LARGE = 'BULK_LOAD_FILE_TOO_LARGE',
  BULK_LOAD_ROW_LIMIT_EXCEEDED = 'BULK_LOAD_ROW_LIMIT_EXCEEDED',
  BULK_LOAD_MISSING_HEADERS = 'BULK_LOAD_MISSING_HEADERS',
  BULK_LOAD_DUPLICATE_HEADER = 'BULK_LOAD_DUPLICATE_HEADER',
  BULK_LOAD_UNKNOWN_HEADER = 'BULK_LOAD_UNKNOWN_HEADER',
  BULK_LOAD_MULTIPLE_SHEETS = 'BULK_LOAD_MULTIPLE_SHEETS',
  BULK_LOAD_PREVIEW_MISMATCH = 'BULK_LOAD_PREVIEW_MISMATCH',
  BULK_LOAD_ALREADY_CONFIRMED = 'BULK_LOAD_ALREADY_CONFIRMED',
  BULK_LOAD_VALIDATION_FAILED = 'BULK_LOAD_VALIDATION_FAILED',
  BULK_LOAD_NO_VALID_ROWS = 'BULK_LOAD_NO_VALID_ROWS',
}

export enum ProductBulkRowErrorCode {
  EMPTY_PRODUCT_NAME = 'EMPTY_PRODUCT_NAME',
  PRODUCT_NAME_TOO_LONG = 'PRODUCT_NAME_TOO_LONG',
  DUPLICATE_PRODUCT_NAME_IN_FILE = 'DUPLICATE_PRODUCT_NAME_IN_FILE',
  PRODUCT_NAME_ALREADY_EXISTS = 'PRODUCT_NAME_ALREADY_EXISTS',
  CATEGORY_EMPTY = 'CATEGORY_EMPTY',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  BASE_UNIT_EMPTY = 'BASE_UNIT_EMPTY',
  BASE_UNIT_NOT_FOUND = 'BASE_UNIT_NOT_FOUND',
  INVALID_COST_NET = 'INVALID_COST_NET',
  INVALID_ACTIVE_PRICE_NET = 'INVALID_ACTIVE_PRICE_NET',
  INVALID_MIN_STOCK = 'INVALID_MIN_STOCK',
  INVALID_INITIAL_STOCK = 'INVALID_INITIAL_STOCK',
  INVALID_MARKUP_PERCENTAGE = 'INVALID_MARKUP_PERCENTAGE',
  INVALID_TAX_TREATMENT = 'INVALID_TAX_TREATMENT',
  INVALID_IVA_PERCENTAGE = 'INVALID_IVA_PERCENTAGE',
  IVA_NOT_ALLOWED = 'IVA_NOT_ALLOWED',
  INVALID_CONVERSIONS_SYNTAX = 'INVALID_CONVERSIONS_SYNTAX',
  CONVERSION_UNIT_NOT_FOUND = 'CONVERSION_UNIT_NOT_FOUND',
  CONVERSION_UNIT_EQUALS_BASE = 'CONVERSION_UNIT_EQUALS_BASE',
  DUPLICATE_CONVERSION_UNIT = 'DUPLICATE_CONVERSION_UNIT',
  INVALID_CONVERSION_FACTOR = 'INVALID_CONVERSION_FACTOR',
  FORMULA_NOT_ALLOWED = 'FORMULA_NOT_ALLOWED',
  STOCK_OVERFLOW = 'STOCK_OVERFLOW',
}
