export enum PurchaseOrderStatus {
  BORRADOR = 'BORRADOR',
  EMITIDA = 'EMITIDA',
  PARCIAL = 'PARCIAL',
  COMPLETADA = 'COMPLETADA',
  CANCELADA = 'CANCELADA',
}

export enum SupplierInvoiceStatus {
  BORRADOR = 'BORRADOR',
  VALIDANDO = 'VALIDANDO',
  OBSERVADA = 'OBSERVADA',
  AUTORIZADA = 'AUTORIZADA',
  CONFIRMADA = 'CONFIRMADA',
}

export enum PurchaseOrderErrorCode {
  PURCHASE_ORDER_NOT_FOUND = 'PURCHASE_ORDER_NOT_FOUND',
  PURCHASE_ORDER_INVALID_STATUS = 'PURCHASE_ORDER_INVALID_STATUS',
  PURCHASE_ORDER_CANNOT_EDIT_NON_DRAFT = 'PURCHASE_ORDER_CANNOT_EDIT_NON_DRAFT',
  PURCHASE_ORDER_CANNOT_EMIT_NON_DRAFT = 'PURCHASE_ORDER_CANNOT_EMIT_NON_DRAFT',
  PURCHASE_ORDER_CANNOT_CANCEL = 'PURCHASE_ORDER_CANNOT_CANCEL',
  PURCHASE_ORDER_EMPTY_ITEMS = 'PURCHASE_ORDER_EMPTY_ITEMS',
  PURCHASE_ORDER_DUPLICATE_ITEM = 'PURCHASE_ORDER_DUPLICATE_ITEM',
  PURCHASE_ORDER_SUPPLIER_NOT_FOUND = 'PURCHASE_ORDER_SUPPLIER_NOT_FOUND',
  PURCHASE_ORDER_SUPPLIER_INACTIVE = 'PURCHASE_ORDER_SUPPLIER_INACTIVE',
  PURCHASE_ORDER_SUPPLIER_CHANGE_REQUIRES_ITEMS = 'PURCHASE_ORDER_SUPPLIER_CHANGE_REQUIRES_ITEMS',
  PURCHASE_ORDER_PRODUCT_NOT_FOUND = 'PURCHASE_ORDER_PRODUCT_NOT_FOUND',
  PURCHASE_ORDER_PRODUCT_INACTIVE = 'PURCHASE_ORDER_PRODUCT_INACTIVE',
  PURCHASE_ORDER_SUPPLIER_PRODUCT_NOT_FOUND = 'PURCHASE_ORDER_SUPPLIER_PRODUCT_NOT_FOUND',
  PURCHASE_ORDER_SUPPLIER_PRODUCT_MISMATCH = 'PURCHASE_ORDER_SUPPLIER_PRODUCT_MISMATCH',
  PURCHASE_ORDER_ASSOCIATION_CHANGED = 'PURCHASE_ORDER_ASSOCIATION_CHANGED',
  PURCHASE_ORDER_INVALID_EXPECTED_DELIVERY_DATE = 'PURCHASE_ORDER_INVALID_EXPECTED_DELIVERY_DATE',
  PURCHASE_ORDER_INVALID_QUANTITY = 'PURCHASE_ORDER_INVALID_QUANTITY',
  PURCHASE_ORDER_INVALID_COST = 'PURCHASE_ORDER_INVALID_COST',
  PURCHASE_ORDER_COST_REQUIRED = 'PURCHASE_ORDER_COST_REQUIRED',
}
