export enum PurchaseOrderStatus {
  BORRADOR = 'BORRADOR',
  EMITIDA = 'EMITIDA',
  PARCIAL = 'PARCIAL',
  COMPLETADA = 'COMPLETADA',
  CANCELADA = 'CANCELADA',
}

export enum SupplierInvoiceStatus {
  BORRADOR = 'BORRADOR',
  VALIDANDO = 'VALIDANDO',
  OBSERVADA = 'OBSERVADA',
  AUTORIZADA = 'AUTORIZADA',
  RECHAZADA = 'RECHAZADA',
  CONFIRMADA = 'CONFIRMADA',
}

export enum SupplierInvoiceQuantityStatus {
  EXACTA = 'EXACTA',
  PARCIAL = 'PARCIAL',
  EXCEDIDA = 'EXCEDIDA',
}

export enum SupplierInvoiceAdjustmentMode {
  AMOUNT = 'AMOUNT',
  PERCENTAGE = 'PERCENTAGE',
}

export enum SupplierInvoiceObservationReason {
  QUANTITY_EXCESS = 'QUANTITY_EXCESS',
  COST_VARIATION = 'COST_VARIATION',
}

export enum SupplierInvoiceCostStatus {
  WITHIN_TOLERANCE = 'WITHIN_TOLERANCE',
  EXCEEDS_TOLERANCE = 'EXCEEDS_TOLERANCE',
  ZERO_BASELINE_UNCHANGED = 'ZERO_BASELINE_UNCHANGED',
  ZERO_BASELINE_INCREASE = 'ZERO_BASELINE_INCREASE',
}

export enum SupplierInvoiceDecisionAction {
  AUTHORIZE = 'AUTHORIZE',
  REJECT = 'REJECT',
}

export enum PurchaseSettingsErrorCode {
  PURCHASE_SETTINGS_INVALID_TOLERANCE = 'PURCHASE_SETTINGS_INVALID_TOLERANCE',
}

export enum SupplierInvoiceErrorCode {
  SUPPLIER_INVOICE_NOT_FOUND = 'SUPPLIER_INVOICE_NOT_FOUND',
  SUPPLIER_INVOICE_RECEIPT_NOT_FOUND = 'SUPPLIER_INVOICE_RECEIPT_NOT_FOUND',
  SUPPLIER_INVOICE_DUPLICATE_NUMBER = 'SUPPLIER_INVOICE_DUPLICATE_NUMBER',
  SUPPLIER_INVOICE_INVALID_NUMBER = 'SUPPLIER_INVOICE_INVALID_NUMBER',
  SUPPLIER_INVOICE_INVALID_DATE = 'SUPPLIER_INVOICE_INVALID_DATE',
  SUPPLIER_INVOICE_EMPTY_ITEMS = 'SUPPLIER_INVOICE_EMPTY_ITEMS',
  SUPPLIER_INVOICE_DUPLICATE_ITEM = 'SUPPLIER_INVOICE_DUPLICATE_ITEM',
  SUPPLIER_INVOICE_ITEM_MISMATCH = 'SUPPLIER_INVOICE_ITEM_MISMATCH',
  SUPPLIER_INVOICE_INVALID_QUANTITY = 'SUPPLIER_INVOICE_INVALID_QUANTITY',
  SUPPLIER_INVOICE_INVALID_COST = 'SUPPLIER_INVOICE_INVALID_COST',
  SUPPLIER_INVOICE_INVALID_TAX = 'SUPPLIER_INVOICE_INVALID_TAX',
  SUPPLIER_INVOICE_ALLOCATION_INCONSISTENT = 'SUPPLIER_INVOICE_ALLOCATION_INCONSISTENT',
  SUPPLIER_INVOICE_CONCURRENCY_CONFLICT = 'SUPPLIER_INVOICE_CONCURRENCY_CONFLICT',
  SUPPLIER_INVOICE_INVALID_STATUS = 'SUPPLIER_INVOICE_INVALID_STATUS',
  SUPPLIER_INVOICE_DECISION_CONFLICT = 'SUPPLIER_INVOICE_DECISION_CONFLICT',
  SUPPLIER_INVOICE_REJECTION_REASON_REQUIRED = 'SUPPLIER_INVOICE_REJECTION_REASON_REQUIRED',
  SUPPLIER_INVOICE_REJECTION_REASON_INVALID = 'SUPPLIER_INVOICE_REJECTION_REASON_INVALID',
}

export enum PurchaseOrderErrorCode {
  PURCHASE_ORDER_NOT_FOUND = 'PURCHASE_ORDER_NOT_FOUND',
  PURCHASE_ORDER_INVALID_STATUS = 'PURCHASE_ORDER_INVALID_STATUS',
  PURCHASE_ORDER_CANNOT_EDIT_NON_DRAFT = 'PURCHASE_ORDER_CANNOT_EDIT_NON_DRAFT',
  PURCHASE_ORDER_CANNOT_EMIT_NON_DRAFT = 'PURCHASE_ORDER_CANNOT_EMIT_NON_DRAFT',
  PURCHASE_ORDER_CANNOT_CANCEL = 'PURCHASE_ORDER_CANNOT_CANCEL',
  PURCHASE_ORDER_EMPTY_ITEMS = 'PURCHASE_ORDER_EMPTY_ITEMS',
  PURCHASE_ORDER_DUPLICATE_ITEM = 'PURCHASE_ORDER_DUPLICATE_ITEM',
  PURCHASE_ORDER_SUPPLIER_NOT_FOUND = 'PURCHASE_ORDER_SUPPLIER_NOT_FOUND',
  PURCHASE_ORDER_SUPPLIER_INACTIVE = 'PURCHASE_ORDER_SUPPLIER_INACTIVE',
  PURCHASE_ORDER_SUPPLIER_CHANGE_REQUIRES_ITEMS = 'PURCHASE_ORDER_SUPPLIER_CHANGE_REQUIRES_ITEMS',
  PURCHASE_ORDER_PRODUCT_NOT_FOUND = 'PURCHASE_ORDER_PRODUCT_NOT_FOUND',
  PURCHASE_ORDER_PRODUCT_INACTIVE = 'PURCHASE_ORDER_PRODUCT_INACTIVE',
  PURCHASE_ORDER_SUPPLIER_PRODUCT_NOT_FOUND = 'PURCHASE_ORDER_SUPPLIER_PRODUCT_NOT_FOUND',
  PURCHASE_ORDER_SUPPLIER_PRODUCT_MISMATCH = 'PURCHASE_ORDER_SUPPLIER_PRODUCT_MISMATCH',
  PURCHASE_ORDER_ASSOCIATION_CHANGED = 'PURCHASE_ORDER_ASSOCIATION_CHANGED',
  PURCHASE_ORDER_INVALID_EXPECTED_DELIVERY_DATE = 'PURCHASE_ORDER_INVALID_EXPECTED_DELIVERY_DATE',
  PURCHASE_ORDER_INVALID_QUANTITY = 'PURCHASE_ORDER_INVALID_QUANTITY',
  PURCHASE_ORDER_INVALID_COST = 'PURCHASE_ORDER_INVALID_COST',
  PURCHASE_ORDER_COST_REQUIRED = 'PURCHASE_ORDER_COST_REQUIRED',
}

export enum GoodsReceiptErrorCode {
  GOODS_RECEIPT_NOT_FOUND = 'GOODS_RECEIPT_NOT_FOUND',
  GOODS_RECEIPT_PURCHASE_ORDER_NOT_FOUND = 'GOODS_RECEIPT_PURCHASE_ORDER_NOT_FOUND',
  GOODS_RECEIPT_INVALID_PURCHASE_ORDER_STATUS = 'GOODS_RECEIPT_INVALID_PURCHASE_ORDER_STATUS',
  GOODS_RECEIPT_DELIVERY_NOTE_REQUIRED = 'GOODS_RECEIPT_DELIVERY_NOTE_REQUIRED',
  GOODS_RECEIPT_DUPLICATE_DELIVERY_NOTE = 'GOODS_RECEIPT_DUPLICATE_DELIVERY_NOTE',
  GOODS_RECEIPT_EMPTY_ITEMS = 'GOODS_RECEIPT_EMPTY_ITEMS',
  GOODS_RECEIPT_DUPLICATE_ITEM = 'GOODS_RECEIPT_DUPLICATE_ITEM',
  GOODS_RECEIPT_ITEM_MISMATCH = 'GOODS_RECEIPT_ITEM_MISMATCH',
  GOODS_RECEIPT_INVALID_QUANTITY = 'GOODS_RECEIPT_INVALID_QUANTITY',
  GOODS_RECEIPT_EXCEEDS_PENDING = 'GOODS_RECEIPT_EXCEEDS_PENDING',
  GOODS_RECEIPT_INVALID_COST = 'GOODS_RECEIPT_INVALID_COST',
  GOODS_RECEIPT_BASE_QUANTITY_NOT_REPRESENTABLE = 'GOODS_RECEIPT_BASE_QUANTITY_NOT_REPRESENTABLE',
  GOODS_RECEIPT_BASE_QUANTITY_OVERFLOW = 'GOODS_RECEIPT_BASE_QUANTITY_OVERFLOW',
  GOODS_RECEIPT_CONCURRENCY_CONFLICT = 'GOODS_RECEIPT_CONCURRENCY_CONFLICT',
}
