export enum SaleStatus {
  BORRADOR = 'BORRADOR',
  CONFIRMADA = 'CONFIRMADA',
  CANCELADA = 'CANCELADA',
}

export enum FiscalDocumentType {
  FACTURA_A = 'FACTURA_A',
  FACTURA_B = 'FACTURA_B',
  NOTA_CREDITO_A = 'NOTA_CREDITO_A',
  NOTA_CREDITO_B = 'NOTA_CREDITO_B',
  NOTA_DEBITO_A = 'NOTA_DEBITO_A',
  NOTA_DEBITO_B = 'NOTA_DEBITO_B',
  REMITO = 'REMITO',
}

export enum ArcaStatus {
  EMITIDO = 'EMITIDO',
  PENDIENTE_FACTURACION = 'PENDIENTE_FACTURACION',
  RECHAZADO = 'RECHAZADO',
}

export type ARCAStatus = ArcaStatus;

export enum SalesErrorCode {
  SALE_NOT_FOUND = 'SALE_NOT_FOUND',
  SALE_INVALID_DATE_RANGE = 'SALE_INVALID_DATE_RANGE',
  SALE_DUPLICATE_PRODUCT = 'SALE_DUPLICATE_PRODUCT',
  SALE_PRICE_FIELDS_NOT_ALLOWED = 'SALE_PRICE_FIELDS_NOT_ALLOWED',
  SALE_CREDIT_REQUIRES_CUSTOMER = 'SALE_CREDIT_REQUIRES_CUSTOMER',
  SALE_CREDIT_REQUIRES_INVOICE = 'SALE_CREDIT_REQUIRES_INVOICE',
  SALE_CREDIT_REQUIRES_CURRENT_ACCOUNT = 'SALE_CREDIT_REQUIRES_CURRENT_ACCOUNT',
  SALE_CASH_INVALID_CURRENT_ACCOUNT = 'SALE_CASH_INVALID_CURRENT_ACCOUNT',
  SALE_CONCURRENCY_CONFLICT = 'SALE_CONCURRENCY_CONFLICT',
}

export enum SaleReturnItemQuality {
  APTO = 'APTO',
  NO_APTO = 'NO_APTO',
}

export enum SaleReturnErrorCode {
  SALE_RETURN_SALE_NOT_FOUND = 'SALE_RETURN_SALE_NOT_FOUND',
  SALE_RETURN_SALE_NOT_CONFIRMED = 'SALE_RETURN_SALE_NOT_CONFIRMED',
  SALE_RETURN_ITEM_NOT_FOUND = 'SALE_RETURN_ITEM_NOT_FOUND',
  SALE_RETURN_ITEM_DOES_NOT_BELONG_TO_SALE = 'SALE_RETURN_ITEM_DOES_NOT_BELONG_TO_SALE',
  SALE_RETURN_DUPLICATE_ITEM = 'SALE_RETURN_DUPLICATE_ITEM',
  SALE_RETURN_INVALID_QUANTITY = 'SALE_RETURN_INVALID_QUANTITY',
  SALE_RETURN_EXCEEDS_ORIGINAL_QUANTITY = 'SALE_RETURN_EXCEEDS_ORIGINAL_QUANTITY',
  SALE_RETURN_NO_ITEMS = 'SALE_RETURN_NO_ITEMS',
  SALE_RETURN_PRODUCT_INACTIVE = 'SALE_RETURN_PRODUCT_INACTIVE',
  SALE_RETURN_CONCURRENCY_CONFLICT = 'SALE_RETURN_CONCURRENCY_CONFLICT',
  SALE_RETURN_IDEMPOTENCY_CONFLICT = 'SALE_RETURN_IDEMPOTENCY_CONFLICT',
  SALE_RETURN_RECEIVABLE_INCONSISTENCY = 'SALE_RETURN_RECEIVABLE_INCONSISTENCY',
}
