export enum StockMovementType {
  ENTRADA_COMPRA = 'ENTRADA_COMPRA',
  SALIDA_VENTA = 'SALIDA_VENTA',
  MERMA = 'MERMA',
  AJUSTE_ENTRADA = 'AJUSTE_ENTRADA',
  AJUSTE_SALIDA = 'AJUSTE_SALIDA',
  DEVOLUCION_CLIENTE = 'DEVOLUCION_CLIENTE',
}

export enum QuarantineStatus {
  EN_CUARENTENA = 'EN_CUARENTENA',
  MERMA_CONFIRMADA = 'MERMA_CONFIRMADA',
  DEVOLUCION_PROVEEDOR = 'DEVOLUCION_PROVEEDOR',
  REINGRESADO_STOCK = 'REINGRESADO_STOCK',
}

export enum StockStatus {
  CRITICAL = 'CRITICAL',
  LOW = 'LOW',
  NORMAL = 'NORMAL',
}

export enum StockImportBatchResult {
  COMPLETED = 'COMPLETED',
}

export enum StockBulkFileErrorCode {
  BULK_LOAD_MISSING_FILE = 'BULK_LOAD_MISSING_FILE',
  BULK_LOAD_INVALID_FILE = 'BULK_LOAD_INVALID_FILE',
  BULK_LOAD_UNSUPPORTED_TYPE = 'BULK_LOAD_UNSUPPORTED_TYPE',
  BULK_LOAD_FILE_TOO_LARGE = 'BULK_LOAD_FILE_TOO_LARGE',
  BULK_LOAD_ROW_LIMIT_EXCEEDED = 'BULK_LOAD_ROW_LIMIT_EXCEEDED',
  BULK_LOAD_MISSING_HEADERS = 'BULK_LOAD_MISSING_HEADERS',
  BULK_LOAD_DUPLICATE_HEADER = 'BULK_LOAD_DUPLICATE_HEADER',
  BULK_LOAD_UNKNOWN_HEADER = 'BULK_LOAD_UNKNOWN_HEADER',
  BULK_LOAD_MULTIPLE_SHEETS = 'BULK_LOAD_MULTIPLE_SHEETS',
  BULK_LOAD_PREVIEW_MISMATCH = 'BULK_LOAD_PREVIEW_MISMATCH',
  BULK_LOAD_ALREADY_CONFIRMED = 'BULK_LOAD_ALREADY_CONFIRMED',
  BULK_LOAD_VALIDATION_FAILED = 'BULK_LOAD_VALIDATION_FAILED',
}

export enum StockBulkRowErrorCode {
  EMPTY_INTERNAL_CODE = 'EMPTY_INTERNAL_CODE',
  INTERNAL_CODE_TOO_LONG = 'INTERNAL_CODE_TOO_LONG',
  DUPLICATE_INTERNAL_CODE = 'DUPLICATE_INTERNAL_CODE',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_INACTIVE = 'PRODUCT_INACTIVE',
  EMPTY_QUANTITY = 'EMPTY_QUANTITY',
  INVALID_QUANTITY = 'INVALID_QUANTITY',
  ZERO_QUANTITY = 'ZERO_QUANTITY',
  NEGATIVE_QUANTITY = 'NEGATIVE_QUANTITY',
  EXCESSIVE_DECIMAL_SCALE = 'EXCESSIVE_DECIMAL_SCALE',
  QUANTITY_OUT_OF_RANGE = 'QUANTITY_OUT_OF_RANGE',
  FORMULA_NOT_ALLOWED = 'FORMULA_NOT_ALLOWED',
  STOCK_OVERFLOW = 'STOCK_OVERFLOW',
}
