export enum StockMovementType {
  ENTRADA_COMPRA = 'ENTRADA_COMPRA',
  SALIDA_VENTA = 'SALIDA_VENTA',
  MERMA = 'MERMA',
  AJUSTE_ENTRADA = 'AJUSTE_ENTRADA',
  AJUSTE_SALIDA = 'AJUSTE_SALIDA',
  DEVOLUCION_CLIENTE = 'DEVOLUCION_CLIENTE',
}

export enum QuarantineStatus {
  EN_CUARENTENA = 'EN_CUARENTENA',
  MERMA_CONFIRMADA = 'MERMA_CONFIRMADA',
  DEVOLUCION_PROVEEDOR = 'DEVOLUCION_PROVEEDOR',
  REINGRESADO_STOCK = 'REINGRESADO_STOCK',
}
